// This file is @generated by tools/gen_items_cpp.py. DO NOT EDIT.

#include <array>
#include <span>
#include <string_view>

#include "bazaararena/data/GeneratedItems.hpp"
#include "bazaararena/core/AbilityDefinition.hpp"
#include "bazaararena/core/AbilityPriority.hpp"
#include "bazaararena/core/AbilityType.hpp"
#include "bazaararena/core/ItemKey.hpp"
#include "bazaararena/core/ItemSize.hpp"
#include "bazaararena/core/ItemTier.hpp"
#include "bazaararena/core/Tag.hpp"
#include "bazaararena/core/Trigger.hpp"
#include "bazaararena/formula/Formula.hpp"
#include "bazaararena/formula/Condition.hpp"
#include "bazaararena/literals/duration.hpp"

namespace bazaararena::data::generated {

using namespace bazaararena::literals::duration_literals;
using namespace bazaararena::condition;

namespace core = bazaararena::core;
namespace formula = bazaararena::formula;

static const std::array<GeneratedItem, 23> kItems = {
    GeneratedItem{
        .key = "三花",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "三花";
    t.desc = "▶ 造成 {Damage} 伤害；使用其他武器时，此物品暴击率提高 {Custom_0%}（限本场战斗）";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Weapon);
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 6_s;
    t.attributes[0][core::ItemKey::Custom_0] = 5;
    t.attributes[1][core::ItemKey::Custom_0] = 10;
    t.attributes[2][core::ItemKey::Custom_0] = 15;
    t.attributes[3][core::ItemKey::Custom_0] = 20;
    t.attributes[4][core::ItemKey::Custom_0] = 20;
    t.attributes[0][core::ItemKey::Damage] = 15;
    t.attributes[1][core::ItemKey::Damage] = 30;
    t.attributes[2][core::ItemKey::Damage] = 60;
    t.attributes[3][core::ItemKey::Damage] = 120;
    t.attributes[4][core::ItemKey::Damage] = 120;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Damage;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Damage;
    }
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::AddAttribute;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::UseItem;
        a.trigger_entries[0].condition = formula::And<SameSide, formula::And<HasTag<core::Tag::Weapon>, DifferentFromCaster>>;
        a.target_condition = SameAsCaster;
        a.value_key = core::ItemKey::Custom_0;
        a.attribute_key = core::ItemKey::CritRate;
        a.target_count_key = core::ItemKey::ModifyAttributeTargetCount;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "举重手套",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "举重手套";
    t.desc = "▶ 武器伤害提高 {Custom_0}（限本场战斗）";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Apparel | core::Tag::Tool);
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 5_s;
    t.attributes[0][core::ItemKey::Custom_0] = 1;
    t.attributes[1][core::ItemKey::Custom_0] = 2;
    t.attributes[2][core::ItemKey::Custom_0] = 3;
    t.attributes[3][core::ItemKey::Custom_0] = 4;
    t.attributes[4][core::ItemKey::Custom_0] = 4;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::AddAttribute;
        a.priority = core::AbilityPriority::High;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = formula::And<SameSide, HasTag<core::Tag::Weapon>>;
        a.value_key = core::ItemKey::Custom_0;
        a.attribute_key = core::ItemKey::Damage;
        a.target_count_key = core::ItemKey::ModifyAttributeTargetCount;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "冰锥",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "冰锥";
    t.desc = "战斗开始时，冻结 {FreezeTargetCount} 件物品 {Freeze} 秒";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    t.attributes[0][core::ItemKey::Freeze] = 3_s;
    t.attributes[1][core::ItemKey::Freeze] = 4_s;
    t.attributes[2][core::ItemKey::Freeze] = 5_s;
    t.attributes[3][core::ItemKey::Freeze] = 6_s;
    t.attributes[4][core::ItemKey::Freeze] = 6_s;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 1;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Freeze;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::BattleStart;
        a.trigger_entries[0].condition = SameSide;
        a.target_condition = DifferentSide;
        a.value_key = core::ItemKey::Freeze;
        a.target_count_key = core::ItemKey::FreezeTargetCount;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "利爪",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "利爪";
    t.desc = "▶ 造成 {Damage} 伤害；此物品能造成双倍暴击伤害";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Weapon);
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 5_s;
    t.attributes[0][core::ItemKey::Damage] = 10;
    t.attributes[1][core::ItemKey::Damage] = 20;
    t.attributes[2][core::ItemKey::Damage] = 40;
    t.attributes[3][core::ItemKey::Damage] = 80;
    t.attributes[4][core::ItemKey::Damage] = 80;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Damage;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Damage;
    }
    t.aura_count = 0;
    {
        auto& g = t.auras[t.aura_count++];
        g.attribute = core::ItemKey::CritDamage;
        g.condition = SameAsCaster;
        g.value = formula::Constant<100>;
        g.percent = true;
    }
    return t;
}(),
    },
    GeneratedItem{
        .key = "刺刀",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "刺刀";
    t.desc = "使用此物品左侧的武器时，造成 {Damage} 伤害";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Weapon);
    t.attributes[0][core::ItemKey::Damage] = 10;
    t.attributes[1][core::ItemKey::Damage] = 20;
    t.attributes[2][core::ItemKey::Damage] = 40;
    t.attributes[3][core::ItemKey::Damage] = 80;
    t.attributes[4][core::ItemKey::Damage] = 80;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Damage;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::UseItem;
        a.trigger_entries[0].condition = formula::And<SameSide, formula::And<LeftOfCaster, HasTag<core::Tag::Weapon>>>;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Damage;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "古董剑",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "古董剑";
    t.desc = "▶ 造成 {Damage} 伤害";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Weapon);
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 5_s;
    t.attributes[0][core::ItemKey::Damage] = 5;
    t.attributes[1][core::ItemKey::Damage] = 10;
    t.attributes[2][core::ItemKey::Damage] = 20;
    t.attributes[3][core::ItemKey::Damage] = 40;
    t.attributes[4][core::ItemKey::Damage] = 40;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Damage;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Damage;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "哈库维发射器",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "哈库维发射器";
    t.desc = "▶ 造成 {Damage} 伤害；弹药：{AmmoCap}";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Large;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 3;
    t.attributes[1][core::ItemKey::Value] = 6;
    t.attributes[2][core::ItemKey::Value] = 12;
    t.attributes[3][core::ItemKey::Value] = 24;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Weapon);
    for (auto& tier : t.attributes) tier[core::ItemKey::AmmoCap] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 3_s;
    t.attributes[0][core::ItemKey::Damage] = 100;
    t.attributes[1][core::ItemKey::Damage] = 200;
    t.attributes[2][core::ItemKey::Damage] = 400;
    t.attributes[3][core::ItemKey::Damage] = 800;
    t.attributes[4][core::ItemKey::Damage] = 800;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Damage;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Damage;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "守护神之壳",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "守护神之壳";
    t.desc = "▶ 获得 {Shield} 护盾；触发剧毒时，为此物品充能 {ChargeSeconds} 秒";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Medium;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Silver;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 2;
    t.attributes[1][core::ItemKey::Value] = 4;
    t.attributes[2][core::ItemKey::Value] = 8;
    t.attributes[3][core::ItemKey::Value] = 16;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Relic);
    for (auto& tier : t.attributes) tier[core::ItemKey::Charge] = 2_s;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 7_s;
    t.attributes[1][core::ItemKey::Shield] = 75;
    t.attributes[2][core::ItemKey::Shield] = 150;
    t.attributes[3][core::ItemKey::Shield] = 300;
    t.attributes[4][core::ItemKey::Shield] = 300;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Shield;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Shield;
    }
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Charge;
        a.priority = core::AbilityPriority::Low;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Poison;
        a.trigger_entries[0].condition = SameSide;
        a.target_condition = SameAsCaster;
        a.value_key = core::ItemKey::Charge;
        a.target_count_key = core::ItemKey::ChargeTargetCount;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "岩浆核心",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "岩浆核心";
    t.desc = "战斗开始时，造成 {Burn} 灼烧";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    t.attributes[0][core::ItemKey::Burn] = 6;
    t.attributes[1][core::ItemKey::Burn] = 9;
    t.attributes[2][core::ItemKey::Burn] = 12;
    t.attributes[3][core::ItemKey::Burn] = 15;
    t.attributes[4][core::ItemKey::Burn] = 15;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Burn;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::BattleStart;
        a.trigger_entries[0].condition = SameSide;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Burn;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "放大镜",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "放大镜";
    t.desc = "▶ 造成 {Damage} 伤害";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Weapon | core::Tag::Tool);
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 6_s;
    t.attributes[0][core::ItemKey::Damage] = 20;
    t.attributes[1][core::ItemKey::Damage] = 40;
    t.attributes[2][core::ItemKey::Damage] = 80;
    t.attributes[3][core::ItemKey::Damage] = 160;
    t.attributes[4][core::ItemKey::Damage] = 160;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Damage;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Damage;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "毒刺",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "毒刺";
    t.desc = "▶ 造成 {Damage} 伤害；▶ 减速 {SlowTargetCount} 件物品 {Slow} 秒；吸血";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Weapon);
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 7_s;
    t.attributes[0][core::ItemKey::Damage] = 5;
    t.attributes[1][core::ItemKey::Damage] = 10;
    t.attributes[2][core::ItemKey::Damage] = 20;
    t.attributes[3][core::ItemKey::Damage] = 40;
    t.attributes[4][core::ItemKey::Damage] = 40;
    for (auto& tier : t.attributes) tier[core::ItemKey::LifeSteal] = 100;
    for (auto& tier : t.attributes) tier[core::ItemKey::Slow] = 1_s;
    t.attributes[0][core::ItemKey::SlowTargetCount] = 1;
    t.attributes[1][core::ItemKey::SlowTargetCount] = 2;
    t.attributes[2][core::ItemKey::SlowTargetCount] = 3;
    t.attributes[3][core::ItemKey::SlowTargetCount] = 4;
    t.attributes[4][core::ItemKey::SlowTargetCount] = 4;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Damage;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Damage;
    }
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Slow;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = DifferentSide;
        a.value_key = core::ItemKey::Slow;
        a.target_count_key = core::ItemKey::SlowTargetCount;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "毒须鲶",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "毒须鲶";
    t.desc = "▶ 造成 {Poison} 剧毒；此物品被加速时，其剧毒提高 {Custom_0}（限本场战斗）";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Aquatic | core::Tag::Friend);
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 5_s;
    t.attributes[0][core::ItemKey::Custom_0] = 2;
    t.attributes[1][core::ItemKey::Custom_0] = 4;
    t.attributes[2][core::ItemKey::Custom_0] = 6;
    t.attributes[3][core::ItemKey::Custom_0] = 8;
    t.attributes[4][core::ItemKey::Custom_0] = 8;
    for (auto& tier : t.attributes) tier[core::ItemKey::Poison] = 3;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Poison;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Poison;
    }
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::AddAttribute;
        a.priority = core::AbilityPriority::Low;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Haste;
        a.trigger_entries[0].condition = TargetSameAsCaster;
        a.target_condition = SameSide;
        a.value_key = core::ItemKey::Custom_0;
        a.attribute_key = core::ItemKey::Poison;
        a.target_count_key = core::ItemKey::ModifyAttributeTargetCount;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "流星索",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "流星索";
    t.desc = "▶ 造成 {Damage} 伤害；▶ 减速 {SlowTargetCount} 件物品 {Slow} 秒；弹药：{AmmoCap}";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Weapon);
    for (auto& tier : t.attributes) tier[core::ItemKey::AmmoCap] = 2;
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 4_s;
    t.attributes[0][core::ItemKey::Damage] = 20;
    t.attributes[1][core::ItemKey::Damage] = 40;
    t.attributes[2][core::ItemKey::Damage] = 80;
    t.attributes[3][core::ItemKey::Damage] = 160;
    t.attributes[4][core::ItemKey::Damage] = 160;
    t.attributes[0][core::ItemKey::Slow] = 2_s;
    t.attributes[1][core::ItemKey::Slow] = 3_s;
    t.attributes[2][core::ItemKey::Slow] = 4_s;
    t.attributes[3][core::ItemKey::Slow] = 5_s;
    t.attributes[4][core::ItemKey::Slow] = 5_s;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 1;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Damage;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Damage;
    }
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Slow;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = DifferentSide;
        a.value_key = core::ItemKey::Slow;
        a.target_count_key = core::ItemKey::SlowTargetCount;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "獠牙",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "獠牙";
    t.desc = "▶ 造成 {Damage} 伤害";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Weapon);
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 3_s;
    t.attributes[0][core::ItemKey::Damage] = 5;
    t.attributes[1][core::ItemKey::Damage] = 10;
    t.attributes[2][core::ItemKey::Damage] = 20;
    t.attributes[3][core::ItemKey::Damage] = 40;
    t.attributes[4][core::ItemKey::Damage] = 40;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Damage;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Damage;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "符文手斧",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "符文手斧";
    t.desc = "▶ 造成 {Damage} 伤害";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Weapon);
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 8_s;
    t.attributes[0][core::ItemKey::Damage] = 15;
    t.attributes[1][core::ItemKey::Damage] = 30;
    t.attributes[2][core::ItemKey::Damage] = 60;
    t.attributes[3][core::ItemKey::Damage] = 120;
    t.attributes[4][core::ItemKey::Damage] = 120;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Damage;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Damage;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "肥皂块",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "肥皂块";
    t.desc = "▶ 治疗 {Heal} 生命值；弹药：6";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::AmmoCap] = 6;
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 2_s;
    t.attributes[0][core::ItemKey::Heal] = 20;
    t.attributes[1][core::ItemKey::Heal] = 40;
    t.attributes[2][core::ItemKey::Heal] = 80;
    t.attributes[3][core::ItemKey::Heal] = 160;
    t.attributes[4][core::ItemKey::Heal] = 160;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Heal;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Heal;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "舱底蠕虫",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "舱底蠕虫";
    t.desc = "敌方使用最左侧的物品时，造成 {Damage} 伤害；吸血";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Weapon);
    t.attributes[0][core::ItemKey::Damage] = 10;
    t.attributes[1][core::ItemKey::Damage] = 20;
    t.attributes[2][core::ItemKey::Damage] = 40;
    t.attributes[3][core::ItemKey::Damage] = 80;
    t.attributes[4][core::ItemKey::Damage] = 80;
    for (auto& tier : t.attributes) tier[core::ItemKey::LifeSteal] = 100;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Damage;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::UseItem;
        a.trigger_entries[0].condition = Leftmost<formula::And<DifferentSide, HasCooldown>>;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Damage;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "蓝蕉",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "蓝蕉";
    t.desc = "▶ 治疗 {Heal} 生命值";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Food);
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 10_s;
    t.attributes[0][core::ItemKey::Heal] = 10;
    t.attributes[1][core::ItemKey::Heal] = 20;
    t.attributes[2][core::ItemKey::Heal] = 40;
    t.attributes[3][core::ItemKey::Heal] = 80;
    t.attributes[4][core::ItemKey::Heal] = 80;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Heal;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Heal;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "藏刃匕首",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "藏刃匕首";
    t.desc = "▶ 造成 {Damage} 伤害；▶ 加速 {HasteTargetCount} 件物品 {Haste} 秒；战斗开始时，获得 {Custom_0} 金币";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Weapon);
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 4_s;
    for (auto& tier : t.attributes) tier[core::ItemKey::Custom_0] = 1;
    t.attributes[0][core::ItemKey::Damage] = 10;
    t.attributes[1][core::ItemKey::Damage] = 20;
    t.attributes[2][core::ItemKey::Damage] = 40;
    t.attributes[3][core::ItemKey::Damage] = 80;
    t.attributes[4][core::ItemKey::Damage] = 80;
    t.attributes[0][core::ItemKey::Haste] = 1_s;
    t.attributes[1][core::ItemKey::Haste] = 2_s;
    t.attributes[2][core::ItemKey::Haste] = 3_s;
    t.attributes[3][core::ItemKey::Haste] = 4_s;
    t.attributes[4][core::ItemKey::Haste] = 4_s;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 1;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Damage;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Damage;
    }
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Haste;
        a.priority = core::AbilityPriority::High;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = SameSide;
        a.value_key = core::ItemKey::Haste;
        a.target_count_key = core::ItemKey::HasteTargetCount;
    }
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::GainGold;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::BattleStart;
        a.trigger_entries[0].condition = SameSide;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Custom_0;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "轻步靴",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "轻步靴";
    t.desc = "相邻物品 {+Custom_0%} 暴击率";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Apparel);
    t.attributes[0][core::ItemKey::Custom_0] = 3;
    t.attributes[1][core::ItemKey::Custom_0] = 6;
    t.attributes[2][core::ItemKey::Custom_0] = 9;
    t.attributes[3][core::ItemKey::Custom_0] = 12;
    t.attributes[4][core::ItemKey::Custom_0] = 12;
    t.ability_count = 0;
    t.aura_count = 0;
    {
        auto& g = t.auras[t.aura_count++];
        g.attribute = core::ItemKey::CritRate;
        g.condition = AdjacentToCaster;
        g.value = formula::Caster<core::ItemKey::Custom_0>;
        g.percent = false;
    }
    return t;
}(),
    },
    GeneratedItem{
        .key = "驯化蜘蛛",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "驯化蜘蛛";
    t.desc = "▶ 造成 {Poison} 剧毒";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Friend);
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 6_s;
    t.attributes[0][core::ItemKey::Poison] = 1;
    t.attributes[1][core::ItemKey::Poison] = 2;
    t.attributes[2][core::ItemKey::Poison] = 3;
    t.attributes[3][core::ItemKey::Poison] = 4;
    t.attributes[4][core::ItemKey::Poison] = 4;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Poison;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Poison;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "鱼饵",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "鱼饵";
    t.desc = "▶ 水系物品的暴击率提高 {Custom_0%}（限本场战斗）；【局外】购买此物品时，获得 1 件食人鱼";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Aquatic | core::Tag::Food);
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 4_s;
    t.attributes[0][core::ItemKey::Custom_0] = 3;
    t.attributes[1][core::ItemKey::Custom_0] = 6;
    t.attributes[2][core::ItemKey::Custom_0] = 9;
    t.attributes[3][core::ItemKey::Custom_0] = 12;
    t.attributes[4][core::ItemKey::Custom_0] = 12;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::AddAttribute;
        a.priority = core::AbilityPriority::High;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = formula::And<SameSide, formula::And<HasTag<core::Tag::Aquatic>, CanCrit>>;
        a.value_key = core::ItemKey::Custom_0;
        a.attribute_key = core::ItemKey::CritRate;
        a.target_count_key = core::ItemKey::ModifyAttributeTargetCount;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "龙涎香",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "龙涎香";
    t.desc = "▶ 获得治疗，等量于此物品的价值的 {Custom_0} 倍；【局外】购买水系物品时，此物品的价值提高 {Custom_1}；【默认】已购买水系物品数量: {Custom_2}";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Aquatic | core::Tag::Relic);
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 4_s;
    t.attributes[0][core::ItemKey::Custom_0] = 1;
    t.attributes[1][core::ItemKey::Custom_0] = 2;
    t.attributes[2][core::ItemKey::Custom_0] = 3;
    t.attributes[3][core::ItemKey::Custom_0] = 4;
    t.attributes[4][core::ItemKey::Custom_0] = 4;
    t.attributes[0][core::ItemKey::Custom_1] = 1;
    t.attributes[1][core::ItemKey::Custom_1] = 2;
    t.attributes[2][core::ItemKey::Custom_1] = 3;
    t.attributes[3][core::ItemKey::Custom_1] = 4;
    t.attributes[4][core::ItemKey::Custom_1] = 4;
    t.attributes[0][core::ItemKey::Custom_2] = 4;
    t.attributes[1][core::ItemKey::Custom_2] = 8;
    t.attributes[2][core::ItemKey::Custom_2] = 12;
    t.attributes[3][core::ItemKey::Custom_2] = 16;
    t.attributes[4][core::ItemKey::Custom_2] = 16;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Heal;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Heal;
    }
    t.aura_count = 0;
    {
        auto& g = t.auras[t.aura_count++];
        g.attribute = core::ItemKey::Heal;
        g.condition = SameAsCaster;
        g.value = formula::Mul<formula::Caster<core::ItemKey::Value>, formula::Caster<core::ItemKey::Custom_0>>;
        g.percent = false;
    }
    {
        auto& g = t.auras[t.aura_count++];
        g.attribute = core::ItemKey::Value;
        g.condition = SameAsCaster;
        g.value = formula::Mul<formula::Caster<core::ItemKey::Custom_1>, formula::Caster<core::ItemKey::Custom_2>>;
        g.percent = false;
    }
    return t;
}(),
    },
};

std::span<const GeneratedItem> GetGeneratedItems() {
    return std::span<const GeneratedItem>(kItems.data(), kItems.size());
}

}  // namespace bazaararena::data::generated
