// This file is @generated by tools/gen_items_cpp.py. DO NOT EDIT.

#include <array>
#include <span>
#include <string_view>

#include "bazaararena/data/GeneratedItems.hpp"
#include "bazaararena/core/AbilityDefinition.hpp"
#include "bazaararena/core/AbilityPriority.hpp"
#include "bazaararena/core/AbilityType.hpp"
#include "bazaararena/core/ItemKey.hpp"
#include "bazaararena/core/ItemSize.hpp"
#include "bazaararena/core/ItemTier.hpp"
#include "bazaararena/core/Tag.hpp"
#include "bazaararena/core/Trigger.hpp"
#include "bazaararena/formula/Formula.hpp"
#include "bazaararena/formula/Condition.hpp"
#include "bazaararena/literals/duration.hpp"

namespace bazaararena::data::generated {

using namespace bazaararena::literals::duration_literals;
using namespace bazaararena::condition;

namespace core = bazaararena::core;
namespace formula = bazaararena::formula;

static const std::array<GeneratedItem, 10> kItems = {
    GeneratedItem{
        .key = "举重手套",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "举重手套";
    t.desc = "▶ 武器伤害提高 {Damage}（限本场战斗）";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Tool | core::Tag::Apparel);
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 5_s;
    t.attributes[0][core::ItemKey::Custom_0] = 1;
    t.attributes[1][core::ItemKey::Custom_0] = 2;
    t.attributes[2][core::ItemKey::Custom_0] = 3;
    t.attributes[3][core::ItemKey::Custom_0] = 4;
    t.attributes[4][core::ItemKey::Custom_0] = 4;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::AddAttribute;
        a.priority = core::AbilityPriority::High;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = formula::And<SameSide, HasTag<core::Tag::Weapon>>;
        a.value_key = core::ItemKey::Custom_0;
        a.attribute_key = core::ItemKey::Damage;
        a.target_count_key = core::ItemKey::ModifyAttributeTargetCount;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "利爪",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "利爪";
    t.desc = "▶ 造成 {Damage} 伤害；此物品能造成双倍暴击伤害";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Weapon);
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 5_s;
    t.attributes[0][core::ItemKey::Damage] = 10;
    t.attributes[1][core::ItemKey::Damage] = 20;
    t.attributes[2][core::ItemKey::Damage] = 40;
    t.attributes[3][core::ItemKey::Damage] = 80;
    t.attributes[4][core::ItemKey::Damage] = 80;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Damage;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Damage;
    }
    t.aura_count = 0;
    {
        auto& g = t.auras[t.aura_count++];
        g.attribute = core::ItemKey::CritDamage;
        g.condition = SameAsCaster;
        g.value = formula::Constant<100>;
        g.percent = true;
    }
    return t;
}(),
    },
    GeneratedItem{
        .key = "古董剑",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "古董剑";
    t.desc = "▶ 造成 {Damage} 伤害";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Weapon);
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 5_s;
    t.attributes[0][core::ItemKey::Damage] = 5;
    t.attributes[1][core::ItemKey::Damage] = 10;
    t.attributes[2][core::ItemKey::Damage] = 20;
    t.attributes[3][core::ItemKey::Damage] = 40;
    t.attributes[4][core::ItemKey::Damage] = 40;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Damage;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Damage;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "岩浆核心",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "岩浆核心";
    t.desc = "战斗开始时，造成 {Burn} 灼烧";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    t.attributes[0][core::ItemKey::Burn] = 6;
    t.attributes[1][core::ItemKey::Burn] = 9;
    t.attributes[2][core::ItemKey::Burn] = 12;
    t.attributes[3][core::ItemKey::Burn] = 15;
    t.attributes[4][core::ItemKey::Burn] = 15;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Burn;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::BattleStart;
        a.trigger_entries[0].condition = SameSide;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Burn;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "放大镜",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "放大镜";
    t.desc = "▶ 造成 {Damage} 伤害";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Tool | core::Tag::Weapon);
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 6_s;
    t.attributes[0][core::ItemKey::Damage] = 20;
    t.attributes[1][core::ItemKey::Damage] = 40;
    t.attributes[2][core::ItemKey::Damage] = 80;
    t.attributes[3][core::ItemKey::Damage] = 160;
    t.attributes[4][core::ItemKey::Damage] = 160;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Damage;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Damage;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "獠牙",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "獠牙";
    t.desc = "▶ 造成 {Damage} 伤害";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Weapon);
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 3_s;
    t.attributes[0][core::ItemKey::Damage] = 5;
    t.attributes[1][core::ItemKey::Damage] = 10;
    t.attributes[2][core::ItemKey::Damage] = 20;
    t.attributes[3][core::ItemKey::Damage] = 40;
    t.attributes[4][core::ItemKey::Damage] = 40;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Damage;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Damage;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "符文手斧",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "符文手斧";
    t.desc = "▶ 造成 {Damage} 伤害";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Weapon);
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 8_s;
    t.attributes[0][core::ItemKey::Damage] = 15;
    t.attributes[1][core::ItemKey::Damage] = 30;
    t.attributes[2][core::ItemKey::Damage] = 60;
    t.attributes[3][core::ItemKey::Damage] = 120;
    t.attributes[4][core::ItemKey::Damage] = 120;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Damage;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Damage;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "蓝蕉",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "蓝蕉";
    t.desc = "▶ 治疗 {Heal} 生命值";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Food);
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 10_s;
    t.attributes[0][core::ItemKey::Heal] = 10;
    t.attributes[1][core::ItemKey::Heal] = 20;
    t.attributes[2][core::ItemKey::Heal] = 40;
    t.attributes[3][core::ItemKey::Heal] = 80;
    t.attributes[4][core::ItemKey::Heal] = 80;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Heal;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Heal;
    }
    t.aura_count = 0;
    return t;
}(),
    },
    GeneratedItem{
        .key = "轻步靴",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "轻步靴";
    t.desc = "相邻物品 {+Custom_0%} 暴击率";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Apparel);
    t.attributes[0][core::ItemKey::Custom_0] = 3;
    t.attributes[1][core::ItemKey::Custom_0] = 6;
    t.attributes[2][core::ItemKey::Custom_0] = 9;
    t.attributes[3][core::ItemKey::Custom_0] = 12;
    t.attributes[4][core::ItemKey::Custom_0] = 12;
    t.ability_count = 0;
    t.aura_count = 0;
    {
        auto& g = t.auras[t.aura_count++];
        g.attribute = core::ItemKey::CritRate;
        g.condition = AdjacentToCaster;
        g.value = formula::Caster<core::ItemKey::Custom_0>;
        g.percent = false;
    }
    return t;
}(),
    },
    GeneratedItem{
        .key = "驯化蜘蛛",
        .templ = []() {
    core::ItemTemplate t;
    t.name = "驯化蜘蛛";
    t.desc = "▶ 造成 {Poison} 剧毒";
    for (auto& tier : t.attributes) tier[core::ItemKey::Size] = core::ItemSize::Small;
    for (auto& tier : t.attributes) tier[core::ItemKey::MinTier] = core::ItemTier::Bronze;
    for (auto& tier : t.attributes) tier[core::ItemKey::Multicast] = 1;
    for (auto& tier : t.attributes) tier[core::ItemKey::CritDamage] = 200;
    for (auto& tier : t.attributes) tier[core::ItemKey::Reload] = 99;
    for (auto& tier : t.attributes) tier[core::ItemKey::ChargeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::HasteTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::SlowTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::FreezeTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ReloadTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::DestroyTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::RepairTargetCount] = 20;
    for (auto& tier : t.attributes) tier[core::ItemKey::ModifyAttributeTargetCount] = 20;
    t.attributes[0][core::ItemKey::Value] = 1;
    t.attributes[1][core::ItemKey::Value] = 2;
    t.attributes[2][core::ItemKey::Value] = 4;
    t.attributes[3][core::ItemKey::Value] = 8;
    t.attributes[4][core::ItemKey::Value] = 32;
    for (auto& tier : t.attributes) tier[core::ItemKey::Tags] = (core::Tag::Friend);
    for (auto& tier : t.attributes) tier[core::ItemKey::Cooldown] = 6_s;
    t.attributes[0][core::ItemKey::Poison] = 1;
    t.attributes[1][core::ItemKey::Poison] = 2;
    t.attributes[2][core::ItemKey::Poison] = 3;
    t.attributes[3][core::ItemKey::Poison] = 4;
    t.attributes[4][core::ItemKey::Poison] = 4;
    t.ability_count = 0;
    {
        auto& a = t.abilities[t.ability_count++];
        a.type = core::AbilityType::Poison;
        a.trigger_entry_count = 1;
        a.trigger_entries[0].trigger = core::Trigger::Cast;
        a.trigger_entries[0].condition = SameAsCaster;
        a.target_condition = Always;
        a.value_key = core::ItemKey::Poison;
    }
    t.aura_count = 0;
    return t;
}(),
    },
};

std::span<const GeneratedItem> GetGeneratedItems() {
    return std::span<const GeneratedItem>(kItems.data(), kItems.size());
}

}  // namespace bazaararena::data::generated
